
data:
  sample_rate: 2000
  segment_length: 2.0
  overlap: 0.5
  bandpass:
    low: 25
    high: 400

mel:
  n_fft: 256
  win_length: 256 
  hop_length: 128
  n_mels: 64
  fmin: 20
  fmax: 400
  power: 2.0